lang = {
	'en': {
		':heading': 'Umentor',
		':p1H': 'Welcome',
		':p1': 'Umentor is a non-profit project of an individual. Dedicated to expanding access to computer science, specifically developing JavaScript scripting language. We focus on serving low-income, under-represented minorities and increasing the participation of women and young people in Indonesia.',
		':p2H': 'Program',
		':p2': 'Our highly immersive, free of cost learning and open classroom training to teach our students both how to write code (practical tools and the basics of computer science) and how to become a software developer (leadership, inclusivity, and career). Our core values ​​are building and contributing to a supportive community; creating and advocating for inclusivity; and teaching and practicing lifelong learning, all in the open sources technology industry.',
		':p3H': 'Inclusivity',
		':p3': 'Students, volunteers and representatives from our sponsoring organizations come to Umentor with an amazing diversity of identities and experiences. We strive to make Umentor an inclusive, safe and fair space for every member of our community. We recognize and celebrate differences along many axes including, but not limited to, race, ethnicity, class, age, religion, physical appearance, abilities, national origin, educational background, and parental status. All diverse people are encouraged to apply and contribute.',
		':p4H': '',
		':p4': '',
		':p5H': '',
		':p5': '',
		':p6H': '',
		':p6': '',
		':p7H': '',
		':p7': '',
		':p8H': '',
		':p8': '',
		':english': 'English',
		':indonesia': 'Indonesia',
		':choose': 'Language',
	},

	'id': {
		':heading': 'Umentor',
		':p1H': 'Selamat datang',
		':p1': 'Umentor adalah proyek nirlaba dari seorang individu. Didedikasikan untuk memperluas akses ke ilmu komputer, khususnya mengembangkan bahasa scripting JavaScript. Kami fokus melayani minoritas yang berpenghasilan rendah, kurang terwakili, dan meningkatkan partisipasi perempuan dan kaum muda di Indonesia. ',
		':p2H': 'Program',
		':p2': 'Kami sangat imersif, bebas biaya belajar dan pelatihan kelas terbuka untuk mengajar siswa kami baik cara menulis kode (alat praktis dan dasar-dasar ilmu komputer) dan bagaimana menjadi pengembang perangkat lunak (kepemimpinan, inklusivitas, dan karier). Nilai-nilai inti kami adalah membangun dan berkontribusi pada komunitas yang mendukung; menciptakan dan mengadvokasi untuk inklusivitas; dan mengajar dan mempraktikkan pembelajaran seumur hidup, semua di industri teknologi sumber terbuka. ',
		':p3H': 'Inklusivitas',
		':p3': 'Siswa, sukarelawan dan perwakilan dari organisasi sponsor kami datang ke Umentor dengan keragaman identitas dan pengalaman yang luar biasa. Kami berupaya menjadikan Umentor ruang yang inklusif, aman, dan adil bagi setiap anggota komunitas kami. Kami mengenali dan merayakan perbedaan sepanjang banyak sumbu termasuk, tetapi tidak terbatas pada, ras, etnis, kelas, usia, agama, penampilan fisik, kemampuan, asal kebangsaan, latar belakang pendidikan, dan status orang tua. Semua orang yang beragam didorong untuk mendaftar dan berkontribusi. ',
		':p4H': '',
		':p4': '',
		':p5H': '',
		':p5': '',
		':p6H': '',
		':p6': '',
		':p7H': '',
		':p7': '',
		':p8H': '',
		':p8': '',
		':english': 'Inggris',
		':indonesia': 'Indonesia',
		':choose': 'Bahasa',
	}
};
